apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
      - name: aceest-fitness-app
        image: srilakshmikalaga/aceest-fitness-app:v2   # BLUE version
        ports:
        - containerPort: 5000
