apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
      - name: aceest-fitness-app
        image: srilakshmikalaga/aceest-fitness-app:v44   # GREEN version
        ports:
        - containerPort: 5000
