apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  selector:
    app: aceest-fitness
    version: blue  # Start with blue version
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort
